---
- hosts: db-master
  become: yes
  gather_facts: no
  become_method: sudo

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - postgresql-contrib
        - postgresql
        - libpq-dev
        - python-psycopg2
        - postgresql-client
        - rsync

  - service:
    name: postgres
    state: stopped

- hosts: db-master
  become: yes
  become_user: root
  gather_facts: no
  become_method: sudo

  vars:
    dbname: ss_demo_1
    dbuser: postgres
    dbpassword: postgres
    pg_version: 9.5
    master_server: 192.168.216.152

  tasks:

  - name: Generate SSH keys
    command: echo "1" | sudo -i ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''

  - name: create pass postgres
    command: echo "1" | sudo -i PGPASSWORD={{dbpassword}} -u {{dbuser}} psql -d template1 -c "ALTER USER {{dbuser}} WITH PASSWORD '{{dbpassword}}';"

  - name: Configure postgres pg_hba
    template: src=pg_hba.conf dest=/etc/postgresql/{{pg_version}}/main/
    notify: restart postgresql

  - name: Configure postgres postgres.conf
    template: src=postgresql.conf dest=/etc/postgresql/{{pg_version}}/main/
    notify: restart postgresql

  - name: Inject SSH public key into remote systemq
    command: echo "1" | sudo -i ssh-copy-id -i /home/peter/.ssh/id_rsa.pub -o StrictHostKeyChecking=no peter@{{slave_server}}

  handlers:
  - name: restart postgresql
    service: name=postgresql state=restarted 
